# Generated by Django 2.1.7 on 2020-04-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completequeue',
            name='script',
            field=models.CharField(max_length=1000000),
        ),
    ]
