# Generated by Django 2.1.7 on 2020-05-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FFASDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_file', models.CharField(max_length=200)),
                ('analysis_name', models.CharField(max_length=200)),
                ('user_id', models.IntegerField()),
                ('profile_out', models.CharField(max_length=200)),
                ('PDB_out', models.CharField(max_length=200)),
                ('SCOP_out', models.CharField(max_length=200)),
                ('PFAM_out', models.CharField(max_length=200)),
                ('Hsapiens', models.CharField(max_length=200)),
                ('COG_out', models.CharField(max_length=200)),
            ],
        ),
    ]
