# Generated by Django 2.1.7 on 2020-04-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchdb_coocurence', '0008_auto_20190601_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColapsedOnEscherichiaSpeciesLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene1', models.CharField(max_length=50)),
                ('gene2', models.CharField(max_length=50)),
                ('together', models.IntegerField()),
                ('first_only', models.IntegerField()),
                ('second_only', models.IntegerField()),
                ('neither', models.IntegerField()),
                ('pvalue', models.DecimalField(decimal_places=100, max_digits=500)),
                ('data_base', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ColapsedOnEscherichiaStrains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene1', models.CharField(max_length=50)),
                ('gene2', models.CharField(max_length=50)),
                ('together', models.IntegerField()),
                ('first_only', models.IntegerField()),
                ('second_only', models.IntegerField()),
                ('neither', models.IntegerField()),
                ('pvalue', models.DecimalField(decimal_places=100, max_digits=500)),
                ('data_base', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ColapsedOnEscherichiaStrainWithingSpecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene1', models.CharField(max_length=50)),
                ('gene2', models.CharField(max_length=50)),
                ('together', models.IntegerField()),
                ('first_only', models.IntegerField()),
                ('second_only', models.IntegerField()),
                ('neither', models.IntegerField()),
                ('pvalue', models.DecimalField(decimal_places=100, max_digits=500)),
                ('data_base', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
